name: fast CI/CD

on:
  push:
    branches: [main]
    paths-ignore:
      - '.gitignore'
      - '.dockerignore'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
     -  uses: actions/checkout@v4
        with:
          fetch-depth: 1

     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v2
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ap-northeast-2

     - name: Login to Amazon ECR
       id: login-ecr
       uses: aws-actions/amazon-ecr-login@v2

     - name: Set Variables
       id: set-var
       run: |
        echo "ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}" >> $GITHUB_ENV
        echo "ECR_REPOSITORY=frontend" >> $GITHUB_ENV
        echo "IMAGE_TAG=${{ github.run_number }}" >> $GITHUB_ENV
        echo "GIT_EMAIL=sy13192@naver.com" >> $GITHUB_ENV
        echo "GIT_NAME=sy13192" >> $GITHUB_ENV

     - name: Docker Image Build
       run: |
          docker build -t ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} .

     - name: Docker Image Push
       run: |
          docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

     - name: Checkout Deployment Repository
       uses: actions/checkout@v4
       with:
          repository: sy13192/dep
          ref: main
          token: ${{ secrets.GH_TOKEN }}

     - name: k8s manifest update
       run: |
          sed -i "s@ \
          image: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:.*@ \
          image: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}@g" deploy.yml

     - name: Commit and Push
       run: |
          git config user.email "$GIT_EMAIL"
          git config user.name "$GIT_NAME"
          git add deploy.yml
          git commit -m "Update image tag to $IMAGE_TAG" || echo "No changes to commit"
          git push origin main
